// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDud6jexbsEznxFXVJK14tJQOQRnS3XKyg',
    appId: '1:580335007120:web:1f5bf2ccc9aa89b873af15',
    messagingSenderId: '580335007120',
    projectId: 'task6-f267d',
    authDomain: 'task6-f267d.firebaseapp.com',
    storageBucket: 'task6-f267d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlgRir4VrRXhTP8D-H57XQ8WP_Jdce9Mg',
    appId: '1:580335007120:android:b2006f6faa06e2f173af15',
    messagingSenderId: '580335007120',
    projectId: 'task6-f267d',
    storageBucket: 'task6-f267d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnVtFAgNFjkJlWRLkYu1ZVcewDGjKrWyc',
    appId: '1:580335007120:ios:a7b0f4b43992ccd773af15',
    messagingSenderId: '580335007120',
    projectId: 'task6-f267d',
    storageBucket: 'task6-f267d.firebasestorage.app',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnVtFAgNFjkJlWRLkYu1ZVcewDGjKrWyc',
    appId: '1:580335007120:ios:a7b0f4b43992ccd773af15',
    messagingSenderId: '580335007120',
    projectId: 'task6-f267d',
    storageBucket: 'task6-f267d.firebasestorage.app',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDud6jexbsEznxFXVJK14tJQOQRnS3XKyg',
    appId: '1:580335007120:web:b02ceb0f4b108cdf73af15',
    messagingSenderId: '580335007120',
    projectId: 'task6-f267d',
    authDomain: 'task6-f267d.firebaseapp.com',
    storageBucket: 'task6-f267d.firebasestorage.app',
  );
}
